/**
 *This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
 *Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
 */

package
{
	import flash.display.Sprite;
	
	import flexUnitTests.MenuSuite;
	import flexUnitTests.TestMenuMediator;
	import flexUnitTests.TestPortfolioView;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		private var flexUnitTests_TestPortfolioView_obj:flexUnitTests.TestPortfolioView;
		private var flexUnitTests_TestMenuMediator_obj:flexUnitTests.TestMenuMediator;
		
		private var flexUnitTests_MenuSuite_obj:flexUnitTests.MenuSuite;
	}
}